#配置文件除了数据库的链接配置,其他配置建议不要修改,否则可能造成程序无法运行
server:
  #  端口
  port: 8888
  error:
    #    自定义错误响应时获取不到exception对象 2.x版本以上 异常类型
    include-exception: true
    # 异常消息
    include-message: always
spring:
  # 以下throw-exception-if-no-handler-found: true add-mappings: false 配置可以全局不和异常 捕获404
  # 解释：
  #spring.mvc.throw-exception-if-no-handler-found
  #使springboot可以捕获到404异常：
  #spring.resources.add-mappings=false
  #一般springboot捕获到404的时候会去加载springboot框架里的404页面，所以不会走我们捕获404异常的代码，
  # 如果要走我们自己的代码，就得禁止静态资源的映射：
  #  static-path-pattern无需更改 否则会引起程序某些上传的文件找不到路径
  mvc:
    static-path-pattern: /static/**
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  servlet:

    multipart:
      #      maxFileSize 是单个文件大小
      max-file-size: 500MB
      #      maxRequestSize是设置总上传的数据大小
      max-request-size: 500MB
  #    连接mysql用 mysql5和mysql8配置不一样
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///springboot_appointment?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC
    username: root
    password: 123456
  #    connection-timeout: 30000 #等待连接池分配连接的超时时间,超过时间还没有分配就发生SQLException 默认30秒
  #    minimum-idle: 5 #最小连接数
  #    maximum-pool-size: 20 #最大连接数
  #    auto-commit: true #自动提交
  #    idle-timeout: 60000 #连接超时的最大时间,超时则被释放,默认10分钟
  #    max-lifetime: 1800000 #连接的生命时长,超时没有被使用则释放,默认30分钟
  #    connection-test-query: select 1
  #    pool-name: DatasourceHikariCP #连接池名称

  #    redis配置 nosql 缓存用
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: 3000  #超时时间 3秒
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
    database: 1

  # 解决bean重复定义的。设置为true时，后定义的bean会覆盖之前定义的相同名称的bean。
  #  那么我们自己应该如何选择呢？
  #  这里笔者认为默认不覆盖比较好。
  #  因为还是推荐一个系统中不要存在名称相同的bean，否则后者覆盖前者，多人分工合作的时候，难以避免某些bean被覆盖，会出现很多诡异的问题 ，甚至会带来线上真实的业务损失。
  main:
    allow-bean-definition-overriding: true
#自定义Windows下的上传、下载静态资源路径
windows:
  resources:
    #    磁盘路径
    path: D:/MyspringBootResources/
#自定义linux下的上传、下载静态资源路径
linux:
  resources:
    #    磁盘路径
    path: /MyspringBootResources/
  #    文件上传大小配置
#第三方操作数据库的增删改查
mybatis-plus:
  configuration:
    #    输出sql语句到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapperscan:
    basepackage: com.my.springboot.**

#自定义参数 生成api接口文档 扫描包设置
swagger2:
  basepackage: com.my.springboot.controller

#自定义token参数
token:
  tokenTimeUnits: "天" #/时间单位 时 分 秒 天 总时间计算tokenTimeUnits*tokenExpiration
  tokenExpiration: 10000 #过期时间
  tokenSignKey: "123456111" #签名
  tokenUserRoleSignKey: "userRole222" #签名
  tokenUuidSignKey: "userRole222" #签名
